### ISSUE TITLE
docs: Add documentation for `useAPS` and add disclaimer for third-party Ads

### ISSUE THREAD

**Issue by GregoryWullimann** [KijijiCA/react-advertising#139]
Hello!

Started using react-advertising recently and it great!

I had some issues with a couple of things

- `useAPS` isn't documented anywhere, had to look for it in the code
- We are using a third-party library for ads as well, which uses prebid and APS, from this library we only need the GAM integration. They were conflicting which others, and in the end was enough to disable both APS and Prebid in this library. Could be worth adding a disclaimer in the README for this specific situation.

**Comment by caffeinated-pixels** [comment]
Thanks for pointing this out, I have updated the configuration documentation: https://github.com/KijijiCA/react-advertising/wiki/Configuration#global-amazon-tam-configuration
