### ISSUE TITLE
pbjs.bidderSettings

### ISSUE THREAD

**Issue by iamdhrooov** [KijijiCA/react-advertising#15]
How can I set pbjs.bidderSettings or maybe other prebid settings in the AdvertisingProvider config?

http://prebid.org/dev-docs/publisher-api-reference.html#module_pbjs.bidderSettings

**Comment by pahund** [comment]
You can use a plugin for setting custom bidder settings, as explained here: https://github.com/technology-ebay-de/react-prebid/wiki/Plugins

Let me know if you need further help, otherwise I'll close this issue.

**Comment by iamdhrooov** [comment]
Great. Thanks. Do you support server-side rendering? It's not working with ssr right now for my setup. Also, can we capture events of ads render such as slot_render_ended, etc

**Comment by pahund** [comment]
What `react-prebid` does is wrap around gpt.js and prebid.js, both of which are purely client-side libraries, so it does not make sense to use it on the server side. When rendering on the server, set the prop `active={false}`, or perhaps use something like `active={typeof window !== 'undefined'}` to make advertising only active when the advertising provider is rendered on the client side.

To capture events like `slot_render_ended`, you can also use the plugin mechanism.
