### ISSUE TITLE
Babel step

### ISSUE THREAD

**Issue by mattcolman** [KijijiCA/react-advertising#18]
Hi, if I create a PR to add a babel step will you be open to that? 
Our webpack code ignores node_modules so we can only see minified code in the react dev tools for this package. Most other packages ship babelified (unminified) code so it plays nice.

**Comment by pahund** [comment]
I'm not sure if I quite understand what you want to do. 

React Prebid provides a packaged version that has been run through babel ([index.js](https://github.com/technology-ebay-de/react-prebid/blob/master/index.js)) as well as a non-packaged ES6 version ([index-esnext.js](https://github.com/technology-ebay-de/react-prebid/blob/master/index-esnext.js)) which you can use if you prefer to transpile the code through your own Babel/webpack setup.

Are you proposing to add another bundle that has not been minified?

**Comment by mattcolman** [comment]
our webpack config is not set up to handle index-esnext.js. We don't want to transpile any third party node modules. So instead we use your index.js, however because it's minified it makes it hard to debug the code. For example using react dev tools I don't see the component names and can't set any breakpoints.

**Comment by mattcolman** [comment]
What's your intended use for index.js? Is this for installation via a script tag? If it's meant for npm installation then I think unminified code is always preferable?

**Comment by pahund** [comment]
Hi Matt, 

your feature request is valid, I've done some research and looked at how other projects are doing this. I've created a separate issue that outlines how I think this should be solved, feel free to provide feedback: 

* #20 – Improve Code Packaging and Delivery

We will have to do a major release for this, as people may rely on the default JS bundle to be minified. I cannot promise any delivery date.

If you want to take care of this in a pull request, I would be very grateful! 😀

**Comment by pahund** [comment]
@mattcolman 
I've published a beta release with your changes: [3.0.0-beta.0](https://www.npmjs.com/package/react-prebid/v/3.0.0-beta.0)

Can you please check if this fixes your issue and confirm? Then I'll release a final version after some more testing on my end.

**Comment by mattcolman** [comment]
yep works for me! Thanks!
