### ISSUE TITLE
feat: Support for enableLazyLoad()

### ISSUE THREAD

**Issue by dsbrianwebster** [KijijiCA/react-advertising#25]
Thanks for the amazing work on this package eBayClassifiedsGroup!

Question. We're trying to accommodate a request of the following Gpt config...

```js
googletag.pubads().enableLazyLoad({
  // Render slots within 1.5 viewports.
  renderMarginPercent: 150,
  mobileScaling: 2.0
 });
```

We tried passing this in plugins like so:

```js
const plugins = [
  {
    setupGpt() {
      window.googletag.pubads().enableLazyLoad({
        // Render slots within 1.5 viewports.
        renderMarginPercent: 150,
        mobileScaling: 2.0,
      })
    },
  },
]
```

However, this seems to have no effect. Is this possible or will it conflict with the default functions like `pubads.disableInitialLoad()` that are run inside of setupGpt?

**Comment by dsbrianwebster** [comment]
I'm thinking this excludes because it's not possible per...
https://github.com/prebid/Prebid.js/issues/3962

If so, what would a good approach to lazyloading be here? If we use an intersection observer to render `<AdvertisingSlot />` we get a bunch of warnings like so..

![image](https://user-images.githubusercontent.com/8154653/94955111-15baf680-04b8-11eb-8913-ed56dc5f5263.png)

**Comment by pahund** [comment]
Hi @dsbrianwebster, I'm sorry, I completely missed your messages 😳 

Did you find a solution for this?

**Comment by mattcolman** [comment]
@dsbrianwebster I ran the code above in the `displaySlots` step rather than `setupGpt` and it works for me. Thanks for the suggestion to try this via a plugin!
