### ISSUE TITLE
Possibility of not calling enableSingleRequest() in setupGpt

### ISSUE THREAD

**Issue by Fumler** [KijijiCA/react-advertising#6]
Hello.

Thanks for creating this package, there are some very good ideas here, but we are experiencing low inscreen in DFP but not in our own tracking.

We think the issue might be in the `setupGpt` function where you call `enableSingleRequest()` - https://github.com/technology-ebay-de/react-prebid/blob/master/src/Advertising.js#L205

And I know you put it plugin support, but since this is called after the plugin is called I'm not sure how to go about changing it.

The specific error from adding `?googfc` to the url on our site is:
`googletag.defineSlot was called more times than there are DIVs in the DOM associated with ad slots while in Single Request Mode. This will impact impression counts.`

Any help would be appreciated.

**Comment by pahund** [comment]
Hi Fredrik, thanks for reaching out! 😀

Perhaps it would help you if I put in a configuration option that allows you to opt-out of single request mode?

**Comment by Fumler** [comment]
That would work

**Comment by Fumler** [comment]
Forked the project and tried removing `enableSingleRequest`, which made the "This will impact impression counts." part of the error from Google console go away, but now we some times do not render every ad on the page.

So I guess this change is not needed after all, for our case it would probably need a bigger change, I assume we would need to define and display the ads in the `activate` call or something. I'll see if I get the time to test it out at some point.

And just for clarification, we are using this with intersection observers, and we call `activate` when the component is in the viewport. We track our ads by listening to GPT events, and everything is good with our own tracking, so everything seems to work as it should. The only problem here is that Google's own reporting (in DFP/Ad Manager) seems to report different numbers than our own, while we see (from GPT events) inscreen numbers around 90%, DFP/Ad Manager reports are saying 25-50%

**Comment by pahund** [comment]
OK, so nothing to do from my side at this point. I'll be happy to review your pull request, if you want to create one. If you do, please make sure your code changes are covered by unit tests.
